<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pd</string>
	</array>
	<key>name</key>
	<string>Paradocs</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>%\\.?</string>
			<key>name</key>
			<string>string.source.paradocs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%""""</string>
			<key>end</key>
			<string>""""</string>
			<key>name</key>
			<string>string.source.paradocs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%"""</string>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.source.paradocs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%""</string>
			<key>end</key>
			<string>""</string>
			<key>name</key>
			<string>string.source.paradocs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%"</string>
			<key>end</key>
			<string>(?&lt;!\\)"</string>
			<key>name</key>
			<string>string.source.paradocs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\.?</string>
			<key>name</key>
			<string>string.source.paradocs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>""""</string>
			<key>end</key>
			<string>""""</string>
			<key>name</key>
			<string>string.source.paradocs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.source.paradocs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>""</string>
			<key>end</key>
			<string>""</string>
			<key>name</key>
			<string>string.source.paradocs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>(?&lt;!\\)"</string>
			<key>name</key>
			<string>string.source.paradocs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%rule</string>
			<key>name</key>
			<string>keyword.source.paradocs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%extend</string>
			<key>name</key>
			<string>keyword.source.paradocs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%def</string>
			<key>name</key>
			<string>keyword.source.paradocs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%escape</string>
			<key>name</key>
			<string>keyword.source.paradocs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%before</string>
			<key>name</key>
			<string>keyword.source.paradocs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%after</string>
			<key>name</key>
			<string>keyword.source.paradocs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%include</string>
			<key>name</key>
			<string>keyword.source.paradocs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%read</string>
			<key>name</key>
			<string>keyword.source.paradocs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%[^"%\s]+</string>
			<key>name</key>
			<string>keyword.source.paradocs</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.paradocs</string>
	<key>uuid</key>
	<string>3101d065-5b5b-4eb9-901f-e42882d644bb</string>
</dict>
</plist>
